### ISSUE TITLE
Mouse control doesn't work from expanded dock

### ISSUE THREAD

**Issue by kirstymcnaught** [JuliusSweetland/OptiKey#133] opened 2015-10-06 08:31 UTC
Using Windows 8.1, bug present in (at least) v2.0.12 and v2.1.0.

Replication steps (v2.0.12)
- Launch OptiKey
- Click "Mouse"
- The small mouse control panel appears
- Click "Left Click"
- The mouse pointer is enlarged, and the next dwell outside the OptiKey panel results in a left click (correct behaviour)
- Click "Expand panel"
- The large mouse control panel appears
- Click "Left Click"
- Nothing happens - no enlarged mouse pointer, no dwell action outside the OptiKey panel (bug)

In v2.1.0, the same behaviour is observed with the expanded mouse panel, except:
- The mouse panel is expanded by default
- The "collapse dock" button is greyed out
- Therefore mouse control doesn't work at all

Demonstration at: https://youtu.be/Im1xjlHEHPM

**Comment by JuliusSweetland** [comment] 2015-10-06 10:18
@kirstymcnaught Thanks for reporting this (and excellent information! I wish everyone supplied videos). The issue is that you are selecting left mouse click AT CURRENT LOCATION.

I maybe need to think about how to make this clearer, but the top set of actions on the expanded mouse screen, under "Do at current location..." perform the mouse action wherever the cursor is currently. As you are controlling OptiKey with your mouse what is happening is the left click is occurring over OptiKey, which has no effect as OptiKey does not react to clicks. If, however, you were using an eye tracker, you might want to move the cursor to a point on the screen, then perform a left click at that point, which is the reason for the whole "Do at current location..." section.

If you look at the lower half of the mouse screen, under "Do at point..." these are the actions you expect. Try the "LEFT CLICK" key just under "Do at point..." and it will allow you to select the point at which the click occurs, just like the collapsed mouse dock.

I'll close this issue, but feel free to reply on here - I still get emails when you reply.

**Closed by JuliusSweetland** 2015-10-06 10:18 UTC

**Comment by kirstymcnaught** [comment] 2015-10-06 10:46
Thanks for the clarification, I'll have a play with the EyeTribe as input. One of the things that I think contributed to my confusion is that I'd been using it in the minimised dock mode, and then when I expanded it, the icons were in a different place but my eye snapped to the closest ones (which happen to be "do at current location") and expected them to behave like the ones in the minimised dock (which happen to be "do at point"). Recognising a familiar icon in an almost-familiar location is much easier than reading instructions!

**Comment by JuliusSweetland** [comment] 2015-10-06 10:50
@kirstymcnaught Absolutely. I now have to decide if it's a good idea to swap them over and risk confusing users who are used to their current locations! Hmm.

**Comment by kirstymcnaught** [comment] 2015-10-06 11:11
I just tried out the 'move to point' then 'click at point' workflow with an EyeTribe, and, wow, that's a very different way to do mouse control. I hadn't come across that workflow before, otherwise I might have been more likely to understand the two different paradigms. How likely is it that a user will frequently switch between the two methods? Having duplicate icons on the same view feels a bit risky regardless of which is at the top. If it was the case that people pick their favourite workflow and use it 90% of the time, then it might be better not to show both sets of controls in the same place. I can't comment on what real users do, though I can raise it with SpecialEffect.

**Comment by JuliusSweetland** [comment] 2015-10-06 12:23
@kirstymcnaught I can't really say how likely it is for a user to want to perform "At current location" actions, but I chose to include them as it facilitates actions which otherwise would be extremely difficult or impossible to perform, such as very precise drag actions, or precisely targeted click actions.

I think that most people won't need any of these extra mouse actions, which is why the mouse keyboard is in a collapsed state by default. It is only when you expand it that you gain access to all of these functions. I could add a setting later to prevent expanding the mouse dock so the whole program can be restricted to a more simplistic model, but I've always taken the approach that I would like to make OptiKey as powerful as possible and scale it back only when needed.
